config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets do
    collection do
      get 'search'
    end
    
    collection do
      get 'about'
    end

    collection do
      get 'portfolio'
    end

    collection do
      get 'contact'
    end

    collection do
      get 'photograph'
    end

    collection do
      get 'video'
    end

    collection do
      get 'tweet'
    end

    collection do
      post 'import'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user

  def self.search(search)
    return Tweet.all unless search
    Tweet.where('text LIKE(?)', "%#{search}%")
  end

  #importメソッド
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      tweet = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      tweet.attributes = row.to_hash.slice(*updatable_attributes)
      tweet.save
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "text", "image", "created_at", "updated_at", "user_id", "name", "adress","area"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :tweet, :show, :search]

  def index
    
  end

  def tweet
    if params[:option] == "A" || params[:option] == nil
          @tweets = Tweet.includes(:user).order("created_at DESC")
    elsif params[:option] == "B"
      @tweets = Tweet.includes(:user).order("area DESC")
    end
    
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end 

  def show
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  def import
    Tweet.import(params[:file])
    redirect_to tweet_tweets_path
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:name, :image, :text, :adress, :area).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id]) 
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def about
  end

  def portfolio
  end

  def contact
  end

  def photograph
  end

  def video
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Myportfolio</title>
    <link href="https://fonts.googleapis.com/css?family=Bitter:400,700" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <%= yield %>

</html>

app/views/tweets/about.html.erb
<body id="about">
  
  <!-- header始まり -->
   <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <li><a href="/tweets/portfolio">Portfolio</a></li>
        <li><a href="/tweets/about">About</a></li>
        <li><a href="/tweets/contact">Contact</a></li>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap">
    <div class="content">
      <div class="main-center">
        <h1>About</h1>
        <p>K STYLE LAB代表、栗原慎也のプロフィールや経歴の紹介ページです。</p>
        <section class="profile clearfix">
          <div class="profile-txt">
            <h2 class="icon">Profile</h2>
            <p><span>K STYLE LAB 代表：栗原　慎也</span><br>
            実家が酒屋であった為、家族の働き方やお店の中で夢中になって遊んでいるうちに自然と商売人としての道を志すようになる。<br>
            大学卒業後、地元佐世保での就職を目指しファッションビル運営のTWINKLEに入社。バイヤー・MDとして商品開発に長く携わる。<br>
            退職後、TECH::EXPERTで畑違いのプログラミングを学び、現在はITを融合させた店舗開発するなどで地元活性に日々精進している。</p>
          </div>
          <img src="/assets/about-profile.png" alt="山田太郎プロフィール画像" class="profile-image">
        </section>
        <section class="career">
          <h2 class="icon">Career and Job history</h2>
          <table>
            <tr>
              <th>2003年3月</th>
              <td>中京大学商学部商学科 卒業　西沢本店に入社</td>
            </tr>
            <tr>
              <th>2019年11月</th>
              <td>西沢本店を退社</td>
            </tr>
            <tr>
              <th>2020年1月</th>
              <td>TECH::EXPERTにてプログラミングを学ぶ</td>
            </tr>
            <tr>
              <th>2020年4月</th>
              <td>「K Style Lab」を設立</td>
            </tr>
            <tr>
              <th>2020年6月</th>
              <td>ポップアップストアとECを融合した新規事業を立上</td>
            </tr>
          </table>
        </section>
      </div>
    </div>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/contact.html.erb
<body id="contact">
  
  <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <li><a href="/tweets/portfolio">Portfolio</a></li>
        <li><a href="/tweets/about">About</a></li>
        <li><a href="/tweets/contact">Contact</a></li>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap">
    <div class="content">
      <div class="main-center">
        <h1>Contact</h1>
        <p>K STYLE LABへのアクセス方法、お問い合わせ、出店のご依頼フォームのページです。お気軽にお問い合わせください。</p>
        <section class="access clearfix">
          <h2 class="icon">Access</h2>
          <table>
            <tr>
              <th>所在地住所</th>
              <td>〒123-4567 長崎県佐世保市○△☆-12</td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td>012-3456-7890</td>
            </tr>
            <tr>
              <th>電車でのアクセス</th>
              <td>JR「佐世保」駅より徒歩1０分</td>
            </tr>
            <tr>
              <th>お車でのアクセス</th>
              <td>佐世保港I.Cより5分</td>
            </tr>
          </table>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3339.91247885299!2d129.72345711519188!3d33.16392448085692!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x356a942dbb85d065%3A0x8a3d23d32e7f9f04!2z5L2Q5LiW5L-d6aeF!5e0!3m2!1sja!2sjp!4v1583130164262!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        </section>
        <section>
          <h2 class="icon">Contact form</h2>
          <div class="form">
            <form>
              <dl>
                <dt><span class="required">お名前</span></dt>
                <dd><input type="text" name="name" class="name" required></dd>
                <dt><span class="required">メールアドレス</span></dt>
                <dd><input type="email" name="email" class="email" required></dd>
                <dt>お電話番号</dt>
                <dd><input type="tel" name="tel" class="tel"></dd>
                <dt>お問合せ種別</dt>
                <dd>
                  <select name="type" class="type">
                    <option value="撮影のご依頼">撮影のご依頼</option>
                    <option value="講演・各種メディア出演のご依頼">講演・各種メディア出演のご依頼</option>
                    <option value="その他お問い合わせ">その他お問い合わせ</option>
                  </select>
                </dd>
                <dt>ご希望のご連絡方法</dt>
                <dd>
                  <input type="radio" name="contact" value="Eメール">Eメール
                  <input type="radio" name="contact" value="お電話">お電話
                </dd>
                <dt>メッセージ</dt>
                <dd><textarea name="message" class="message"></textarea></dd>
              </dl>
              <button type="submit">送信</button>
            </form>
            <div class="attention">
              <p>※ 「<span class="required"></span>」の付いている項目は必須項目です。<br>※メッセージ送信後、48時間以内に担当者よりご連絡いたします。</p>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets/tweet">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/tweets/tweet">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<body id="contact">
  
  <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <% if user_signed_in? %>
          <li><%= current_user.nickname %></li>
          <li id="store"><a href="/tweets/tweet">Store</a></li>
          <li id="store"><a href="/tweets/new">New</a></li>
          <li><%= link_to "MyPage", "/users/#{current_user.id}" %></li>
          <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "LogIn", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "NewUser", new_user_registration_path, class: 'post' %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <div class="contents row">
          <div class="container">
            <%= form_with(model: @tweet, local: true) do |form| %>
              <h3>
                編集する
              </h3>
              <%= form.text_field :image, placeholder: "Image Url" %>
              <%= form.text_area :text, placeholder: "text" , rows: "10" %>
              <%= form.submit "SEND" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <aside class="sidebar">
        <section>
          <h2>Store Location</h2>
          <ul>
            <li><a href="">北海道</a></li>
            <li><a href="">東北</a></li>
            <li><a href="">関東</a></li>
            <li><a href="">東海</a></li>
            <li><a href="">関西</a></li>
            <li><a href="">中国・四国</a></li>
            <li><a href="">九州</a></li>
          </ul>
        </section>
        
      </aside>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/index.html.erb
<body id="index">
  
  <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="/"><img src="assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <% if user_signed_in? %>
          <li><%= current_user.nickname %></li>
          <li id="store"><a href="/tweets/tweet">Store</a></li>
          <li id="store"><a href="/tweets/new">New</a></li>
          <li><%= link_to "MyPage", "/users/#{current_user.id}" %></li>
          <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "LogIn", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "NewUser", new_user_registration_path, class: 'post' %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap">
    <div class="content">
      <h1>No shopping No life, Let's go to Town!!</h1>
      <p>このWebサイトは、学習用サンプルとして作成する「K Style Lab」という架空の写真投稿＆ポートフォリオサイトです。<br></p>
      <p class="btn"><a href="/tweets/portfolio">My Portfolio</a></p>
    </div>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2020 Shinya-Kurihara.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/new.html.erb
<body id="contact">
  
  <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <% if user_signed_in? %>
          <li><%= current_user.nickname %></li>
          <li id="store"><a href="/tweets/tweet">Store</a></li>
          <li id="store"><a href="/tweets/new">New</a></li>
          <li><%= link_to "MyPage", "/users/#{current_user.id}" %></li>
          <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "LogIn", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "NewUser", new_user_registration_path, class: 'post' %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <div class="contents row">
          <div class="container">
            <%= form_with(model: @tweet, local: true) do |form| %>
              <h3>
                投稿する
              </h3>
              <%= form.text_area :name, placeholder: "name" , rows: "1" %>
              <%= form.text_area :text, placeholder: "perfecture" , rows: "1" %>
              <%= form.text_area :adress, placeholder: "adress" , rows: "1" %>
              <%= form.text_field :image, placeholder: "Image Url" %>
              
              <%= form.submit "SEND" %>
            <% end %>
            <%= form_tag import_tweets_path, multipart: true do %>
              <%= file_field_tag :file %>
              <%= submit_tag "インポート" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/photograph.html.erb
<body id="photograph">
  
　<!--  headerの始まり-->
  <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <li><a href="/tweets/portfolio">Portfolio</a></li>
        <li><a href="/tweets/about">About</a></li>
        <li><a href="/tweets/contact">Contact</a></li>
      </ul>
    </nav>
  </header>
　<!--  headerの終わり-->
  
　<!--  wrapの始まり-->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <h1>Photograph</h1>
        <p>これまでに立上げた店舗・業態・アプリを掲載しております</p>
        <section id="city">
          <h2 class="icon">SHOP</h2>
          <ul class="clearfix photograph-list">
            <li><img src="/assets/photograph-city-01.png" alt="駅への階段"></li>
            <li><img src="/assets/photograph-city-02.png" alt="自転車とシャッター"></li>
            <li><img src="/assets/photograph-city-03.png" alt="スケートパーク"></li>
            <li><img src="/assets/photograph-city-04.png" alt="エアポート"></li>
            <li><img src="/assets/photograph-city-05.png" alt="雑貨を扱う店舗"></li>
            <li><img src="/assets/photograph-city-06.png" alt="ストリートバスケ"></li>
          </ul>
        </section>
        <section id="beach">
          <h2 class="icon">ITEM</h2>
          <ul class="clearfix photograph-list">
            <li><img src="/assets/photograph-beach-01.png" alt="海水浴場"></li>
            <li><img src="/assets//photograph-beach-02.png" alt="ビーチへ続く道"></li>
            <li><img src="/assets//photograph-beach-03.png" alt="離れ小島"></li>
            <li><img src="/assets//photograph-beach-04.png" alt="岩場と波"></li>
            <li><img src="/assets//photograph-beach-05.png" alt="ヤシの木"></li>
            <li><img src="/assets//photograph-beach-06.png" alt="波打ち際"></li>
          </ul>
        </section>
        <section id="forest">
          <h2 class="icon">APP</h2>
          <ul class="clearfix photograph-list">
            <li><img src="/assets//photograph-forest-01.png" alt="池と小舟"></li>
            <li><img src="/assets//photograph-forest-02.png" alt="可憐な花"></li>
            <li><img src="/assets//photograph-forest-03.png" alt="森の小径"></li>
            <li><img src="/assets//photograph-forest-04.png" alt="清流をカップで掬う"></li>
            <li><img src="/assets//photograph-forest-05.png" alt="焚き火台"></li>
            <li><img src="/assets//photograph-forest-06.png" alt="新芽と若葉"></li>
          </ul>
        </section>
      </div>
      <aside class="sidebar">
        <section>
          <h2>Photograph</h2>
          <ul>
            <li><a href="photograph.html#city">店舗-Shop</a></li>
            <li><a href="photograph.html#beach">商品-Item</a></li>
            <li><a href="photograph.html#forest">アプリ-App</a></li>
          </ul>
        </section>
        <section>
          <h2>Video</h2>
          <ul>
            <li><a href="video.html#movie">Movie</a></li>
            <li><a href="video.html#short-film">Short film</a></li>
          </ul>
        </section>
      </aside>
    </div>
  </div>
  <!-- wrapの終わり-->
  
  <!--  footer始まり-->
  <footer>
    <small>(c)2017 Hattori-studio.</small>
  </footer>  
  <!--  footer終わり-->
  
</body>

app/views/tweets/portfolio.html.erb
<body id="portfolio">
  
  <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <li><a href="/tweets/portfolio">Portfolio</a></li>
        <li><a href="/tweets/about">About</a></li>
        <li><a href="/tweets/contact">Contact</a></li>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <h1>Portofolio</h1>
        <p>これまでに立上げた店舗・業態・アプリを掲載しております</p>
        <section>
          <h2><a href="/tweets/photograph"><img src="/assets/portfolio-photo.jpg" alt="PHOTOGRAPH"></a></h2>
          <p>K Style Labで今まで手がけた「店舗」「商品」「アプリ」の3つのカテゴリでご紹介。<a href="/tweets/photograph">詳しくみる ≫</a></p>
        </section>
        <section>
          <h2><a href="video.html"><img src="/assets/portfolio-video.jpg" alt="VIDEO"></a></h2>
          <p>K Style Labではイベントやキャンペーン・ポップアップストアの動画を随時更新していきます。<a href="video.html">詳しくみる ≫</a></p>
        </section>
      </div>
      <aside class="sidebar">
        <section>
          <h2>Photograph</h2>
          <ul>
            <li><a href="photograph.html#city">店舗-Shop</a></li>
            <li><a href="photograph.html#beach">商品-Item</a></li>
            <li><a href="photograph.html#forest">アプリ-App</a></li>
          </ul>
        </section>
        <section>
          <h2>Video</h2>
          <ul>
            <li><a href="video.html#movie">Movie</a></li>
            <li><a href="video.html#short-film">Short film</a></li>
          </ul>
        </section>
      </aside>
    </div>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/search.html.erb
<body id="contact">
  
  <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <% if user_signed_in? %>
          <li><%= current_user.nickname %></li>
          <li id="store"><a href="/tweets/tweet">Store</a></li>
          <li id="store"><a href="/tweets/new">New</a></li>
          <li><%= link_to "MyPage", "/users/#{current_user.id}" %></li>
          <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "LogIn", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "NewUser", new_user_registration_path, class: 'post' %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <h1>Store</h1>
        <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "都道府県を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
        <p>検索結果</p>
        <div class="contents row clearfix">
          <% @tweets.each do |tweet| %>
            <div class="content_post" style="background-image: url(<%= tweet.image %>);">
              <div class="more">
                <span><%= image_tag 'arrow_top.png' %></span>
                <ul class="more_list">
                  <li>
                    <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
                  </li>
                  <% if user_signed_in? && current_user.id == tweet.user_id %>
                    <li>
                      <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
                    </li>
                    <li>
                      <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <aside class="sidebar">
        <section>
          <h2>Store Location</h2>
          <ul>
            <li><a href="">北海道</a></li>
            <li><a href="">東北</a></li>
            <li><a href="">関東</a></li>
            <li><a href="">東海</a></li>
            <li><a href="">関西</a></li>
            <li><a href="">中国・四国</a></li>
            <li><a href="">九州</a></li>
          </ul>
        </section>
      </aside>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/tweet.html.erb
<body id="contact">
  
  <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="/"><img src="/assets/logo5.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <% if user_signed_in? %>
          <li><%= current_user.nickname %></li>
          <li id="store"><a href="/tweets/tweet">Store</a></li>
          <li id="store"><a href="/tweets/new">New</a></li>
          <li><%= link_to "MyPage", "/users/#{current_user.id}" %></li>
          <li><%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "LogIn", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "NewUser", new_user_registration_path, class: 'post' %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->
  
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <h1>Store Search</h1>
        <p>日本全国のショッピングモールを掲載しています。</p>
        <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "都道府県を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
        <a href="/tweets/tweet/?option=B">営業面積順</a>
        <div class="contents row clearfix">
          <% @tweets.each do |tweet| %>
            <div class="content_post" style="background-image: url(<%= tweet.image %>);">
            <%= tweet.area %>㎡<br>
              <div class="more">
                <span><%= image_tag 'arrow_top.png' %></span>
                <ul class="more_list">
                  <li>
                    <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
                  </li>
                  <% if user_signed_in? && current_user.id == tweet.user_id %>
                    <li>
                      <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
                    </li>
                    <li>
                      <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <aside class="sidebar">
        <section>
          <h2>Store Location</h2>
          <ul>
            <li><a href="">北海道</a></li>
            <li><a href="">東北</a></li>
            <li><a href="">関東</a></li>
            <li><a href="">東海</a></li>
            <li><a href="">関西</a></li>
            <li><a href="">中国・四国</a></li>
            <li><a href="">九州</a></li>
          </ul>
        </section>
        
      </aside>
    </div>
  </div>
  <!-- wrap終わり -->
  
  <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->
  
</body>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/tweets/tweet">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>

  <% @tweets.each do |tweet| %>
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <%= simple_format(tweet.text) %>
    </div>
  <% end %>
</div>